name: testing npm publish

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "got from update foundation ${{ inputs.version }}"
