name: testing npm publish

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
env:
  production: true

jobs:
  generate_json:
    runs-on: ubuntu-latest
    steps:
    - run: echo "got from update foundation ${{ inputs.version }}"
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: npm ci
    - run: node foundation-generator.js ${{ inputs.version }}
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: KANGHO LEE
        author_email: cannalee90@gmail.com
        message: 'generator update'
        add: '*.json'
