name: Trigger foundation upgrade
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version number'
        required: true
        default: '0.0.0'

jobs:
  update-foundation-from-db:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "- in ${{ github.event.inputs.version }}"
  call-workflow-passing-data:
    - name: run generator
      permissions:
        contents: read
        pull-requests: write
      uses: ./.github/workflows/testing-npm-publish.yml
      with:
        version: ${{ github.event.inputs.version }}
  change-commit:
    - name: Commit changes
      needs: call-workflow-passing-data
      uses: EndBug/add-and-commit@v9
        with:
          author_name: KANGHO LEE
          author_email: cannalee90@gmail.com
          message: 'generator update'
          add: '*.json'
