name: Trigger foundation upgrade
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'location'
        required: true
        default: '1.0.0'

jobs:
  update-foundation-from-db:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "- in ${{ github.event.inputs.version }}"
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: team-auspicious/foundation/.github/workflows/testing-npm-publish.yml@master
    with:
      version: ${{ github.event.inputs.version }}
