name: Trigger foundation upgrade
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version number'
        required: true
        default: '0.0.0'

jobs:
  update-foundation-from-db:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "- in ${{ github.event.inputs.version }}"
env:
  production: true
  
jobs:
  generate_json:
    runs-on: ubuntu-latest
    steps:
    - run: echo "got from update foundation ${{ inputs.version }}"
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: npm ci
    - run: node foundation-generator.js ${{ inputs.version }}
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: KANGHO LEE
        author_email: cannalee90@gmail.com
        message: 'generator update'
        add: '*.json'
  patch-version:
    needs: generate_json
    runs-on: ubuntu-latest
    steps:
    - uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: ${{secrets.MY_PAT}}    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: git pull --rebase
      run: git pull --rebase     
    - name: npm version up
      run: npm version ${{ inputs.version }}
    - name: git push master
      run: git push origin master --tag

