name: Trigger foundation upgrade
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'location'
        required: true
        default: '1.0.0'

jobs:
  update-foundation-from-db:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "- in ${{ github.event.inputs.version }}"